#数据库 端口 springMVC相关：json装转换data类型 MyBatis

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/drug?useSSL=FALSE&serverTimezone=UTC
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#配置MyBatis
mybatis:
  mapper-locations: classpath:/mappers/*.xml

#配置端口
server:
  port: 8081